from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
from decimal import Decimal

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='OfferwallProvider', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=100,unique=True)),('slug',models.SlugField(unique=True)),('secret_key',models.CharField(max_length=255)),('is_active',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name='Task', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=200)),('description',models.TextField()),('content_url',models.URLField()),('reward',models.DecimalField(decimal_places=6,max_digits=12,validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),('watch_seconds',models.PositiveIntegerField(default=30)),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name='Wallet', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('balance',models.DecimalField(decimal_places=6,default=Decimal('0'),max_digits=14)),('updated_at',models.DateTimeField(auto_now=True)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='wallet',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Withdrawal', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('amount',models.DecimalField(decimal_places=6,max_digits=14,validators=[django.core.validators.MinValueValidator(Decimal('1'))])),('wallet_address',models.CharField(max_length=255)),('network',models.CharField(default='TRC20',max_length=20)),('status',models.CharField(choices=[('pending','قيد المراجعة'),('approved','مقبول'),('rejected','مرفوض'),('paid','تم الدفع')],default='pending',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='withdrawals',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='TaskCompletion', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('comment',models.TextField()),('rating',models.PositiveSmallIntegerField()),('reward',models.DecimalField(decimal_places=6,max_digits=12)),('completed_at',models.DateTimeField(auto_now_add=True)),('task',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='completions',to='core.task')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='task_completions',to=settings.AUTH_USER_MODEL))], options={'constraints':[models.UniqueConstraint(fields=('user','task'),name='unique_user_task_completion')]}),
        migrations.CreateModel(name='OfferwallTransaction', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('transaction_id',models.CharField(max_length=255)),('reward',models.DecimalField(decimal_places=6,max_digits=14,validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),('created_at',models.DateTimeField(auto_now_add=True)),('provider',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='transactions',to='core.offerwallprovider')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='offerwall_transactions',to=settings.AUTH_USER_MODEL))], options={'constraints':[models.UniqueConstraint(fields=('provider','transaction_id'),name='unique_offerwall_transaction')]})
    ]
